// Generated by scripts/front-page.mjs from patterns/. Do not edit it: run `node scripts/front-page.mjs`.
// Whom each built-in template credits, by the template's id: the ones that credit anyone.
// apps/web/test/front.test.ts draws it again from the app's source and fails when this file is stale.
import type { TemplateCredit } from "@grooph/core";

export const BUILT_IN_CREDITS: Readonly<Record<string, readonly TemplateCredit[]>> = {
  "gauntlet-decomposed": [
    {
      "name": "Matt Shumer's Gauntlet Loop and the Claude of Duty repository",
      "url": "https://github.com/mshumer/Claude-of-Duty",
      "note": "decompose, then builder plus fresh critic per piece against a real reference, blind side by side; here bounded, and pieces run in sequence because the repository's own note says fan-out lost on coupled work"
    }
  ],
  "merge-queue": [
    {
      "name": "Steve Yegge's Gas Town Refinery",
      "url": "https://github.com/gastownhall/gastown",
      "note": "a merge queue that integrates a batch, bisects on failure and lands by a human's word"
    },
    {
      "name": "Bors",
      "url": "https://github.com/bors-ng/bors-ng",
      "note": "batch then bisect"
    }
  ],
  "ownership-not-swarm": [
    {
      "name": "Claude of Duty process note (Matt Shumer)",
      "url": "https://github.com/mshumer/Claude-of-Duty",
      "note": "sequential ownership beat parallel fan-out on coupled systems in the repository's own write-up"
    }
  ],
  "patrol-pulse": [
    {
      "name": "u/croovies's \"Lloyd\" heartbeat orchestrator, as written up by explainx.ai (2026-08-14; a secondary source)",
      "url": "https://www.explainx.ai/blog/claude-code-loop-orchestrator-heartbeat-ticket-memory-august-2026",
      "note": "a standing checklist per pulse, a read-only investigator, findings to a durable ticket store, humans prioritize"
    },
    {
      "name": "Steve Yegge's Gas Town patrols",
      "url": "https://github.com/gastownhall/gastown",
      "note": "patrol agents that loop by design; here one pulse is one run"
    }
  ],
  "ralph-loop": [
    {
      "name": "Geoffrey Huntley's ralph loop",
      "url": "https://ghuntley.com/ralph/",
      "note": "one prompt piped into a fresh session per pass; one item of work per pass from a plan file; state on disk; the human as the brake, here replaced by stops"
    }
  ],
  "spec-then-loop": [
    {
      "name": "Answer-key-first Gauntlet, a community modification of Matt Pocock's Wayfinder",
      "url": "https://github.com/mattpocock/skills/blob/main/docs/engineering/wayfinder.md",
      "note": "write the spec and a pass/fail answer key before the loop; the modification is known from a secondary write-up, not a primary source"
    }
  ],
  "taste-polish": [
    {
      "name": "Matt Shumer's Gauntlet Loop (Claude of Duty)",
      "url": "https://github.com/mshumer/Claude-of-Duty",
      "note": "the bounded form of the Gauntlet: one owner, an isolated critic against a named reference, real stops"
    }
  ]
};
