#!/usr/bin/env node
/**
 * Generate what the app shows of the built-in templates before it has fetched them (slice 0093):
 *
 *   apps/web/src/ui/landing/front.generated.ts   the front page's picture and its six tiles
 *   apps/web/src/doc/credits.generated.ts        whom each built-in template credits, for the compare view
 *
 * The twenty pattern documents weigh 23 KB compressed and were part of every first load, to draw one picture and
 * six glyphs on the front page. They are a piece of the app fetched when a screen needs them now
 * (apps/web/src/doc/builtins.ts), and the front page carries the picture and the glyphs as they are drawn here,
 * in a piece of its own that only its address asks for (apps/web/src/ui/landing/front.ts).
 *
 *   node scripts/front-page.mjs           write them
 *   node scripts/front-page.mjs --check   exit 1 when either is stale or missing
 *
 * Needs @grooph/core built (`pnpm -r build`). The drawing is core's, through the door the app starts from: the
 * same `instantiate`, `picture` and `glyph` the front page called. apps/web/test/front.test.ts draws both again
 * from the app's own source and compares, in `pnpm -r test`, so a pattern changed without this being run fails there.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const core = await import(join(root, "packages/core/dist/src/base.js")).catch(() => {
  console.error("front-page: @grooph/core is not built; run `pnpm -r build` first");
  process.exit(2);
});
const { parseGraphText, instantiate, picture, glyph } = core;

/** The template the front page draws, and the one "Open a template" opens. */
const HERO = "review-gate";
/** The graph it is drawn as: the template's own examples in its slots, and this name and task. */
const HERO_NAME = "Add slugify, reviewed";
const HERO_TASK = "Add a slugify(text) function to src/strings.ts.";
/** The strip: six whole graphs whose shapes differ at a glance. */
const STRIP = ["grind-loop", "spec-then-loop", "metric-sandwich", "heterogeneous-critic", "tournament-then-judge", "patrol-pulse"];
/** A glyph wider than this is a sliver in a thumbnail box (apps/web/src/ui/Glyph.tsx). */
const LONG = 300;

const patterns = join(root, "patterns");
const template = (id) => {
  const doc = parseGraphText(readFileSync(join(patterns, `${id}.grooph.json`), "utf8")).doc;
  if (!doc?.template) {
    console.error(`front-page: patterns/${id}.grooph.json is not a template document`);
    process.exit(1);
  }
  return doc;
};

const hero = template(HERO);
const values = Object.fromEntries((hero.template.slots ?? []).map((slot) => [slot.key, slot.example ?? ""]).filter(([, v]) => v !== ""));
values.task = HERO_TASK;
const heroSvg = picture(instantiate(hero, { name: HERO_NAME, values }), { theme: "auto" });
const tiles = STRIP.map((id) => {
  const doc = template(id);
  const svg = glyph(doc);
  return { id, title: doc.template.title, glyph: svg, long: Number(/viewBox="\S+ \S+ (\S+) \S+"/.exec(svg)?.[1] ?? 0) > LONG };
});

const credits = {};
for (const file of readdirSync(patterns).filter((name) => name.endsWith(".grooph.json")).sort()) {
  const doc = template(file.replace(/\.grooph\.json$/, ""));
  if (doc.template.credits?.length) credits[doc.id] = doc.template.credits;
}

const head = (what) =>
  `// Generated by scripts/front-page.mjs from patterns/. Do not edit it: run \`node scripts/front-page.mjs\`.\n// ${what}\n// apps/web/test/front.test.ts draws it again from the app's source and fails when this file is stale.\n`;
const files = {
  "apps/web/src/ui/landing/front.generated.ts":
    head("The front page's picture and its six tiles, as core draws them from the built-in templates.") +
    `\n/** The template the front page draws, and the one "Open a template" opens. */\nexport const HERO = ${JSON.stringify(HERO)};\n` +
    `\n/** It as a graph, its slots filled with its own examples: core's picture, in the theme that follows the page. */\nexport const HERO_SVG = ${JSON.stringify(heroSvg)};\n` +
    `\n/** The strip: a template's id and title, its glyph, and whether the glyph is too long for a thumbnail's box. */\nexport const TILES: readonly { id: string; title: string; glyph: string; long: boolean }[] = ${JSON.stringify(tiles, null, 2)};\n`,
  "apps/web/src/doc/credits.generated.ts":
    head("Whom each built-in template credits, by the template's id: the ones that credit anyone.") +
    `import type { TemplateCredit } from "@grooph/core";\n\nexport const BUILT_IN_CREDITS: Readonly<Record<string, readonly TemplateCredit[]>> = ${JSON.stringify(credits, null, 2)};\n`,
};

const check = process.argv.includes("--check");
let stale = 0;
for (const [path, text] of Object.entries(files)) {
  const file = join(root, path);
  const now = existsSync(file) ? readFileSync(file, "utf8") : undefined;
  if (now === text) continue;
  if (check) {
    console.error(`front-page: ${path} is ${now === undefined ? "missing" : "stale"}. Run node scripts/front-page.mjs.`);
    stale++;
  } else {
    writeFileSync(file, text);
    console.log(`wrote ${path}`);
  }
}
if (check && stale === 0) console.log("front-page: both files are current");
process.exit(stale > 0 ? 1 : 0);
