#!/usr/bin/env node
/**
 * Generate patterns/index.json and patterns/README.md from the pattern
 * documents in patterns/ (docs/templates.md §3, §5). Both are committed.
 *
 *   node scripts/patterns-index.mjs           write them
 *   node scripts/patterns-index.mjs --check   exit 1 when either is stale (CI)
 *
 * Needs @grooph/core built (`pnpm -r build`): the index rows come from
 * `templateIndexEntry`, the same function the CLI uses for user registries.
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dir = join(root, "patterns");
const core = await import(join(root, "packages/core/dist/src/index.js")).catch(() => {
  console.error("patterns-index: @grooph/core is not built; run `pnpm -r build` first");
  process.exit(2);
});
const { parseGraphText, templateIndex, templateIndexEntry, formatIssue } = core;

const problems = [];
const docs = [];
for (const file of readdirSync(dir).filter((name) => name.endsWith(".grooph.json")).sort()) {
  const parsed = parseGraphText(readFileSync(join(dir, file), "utf8"));
  if (!parsed.doc) {
    problems.push(`${file}: does not match the schema`, ...parsed.issues.map((issue) => `  ${formatIssue(issue)}`));
    continue;
  }
  if (!parsed.doc.template) problems.push(`${file}: has no template block, so it is not a pattern`);
  else if (file !== `${parsed.doc.id}.grooph.json`) problems.push(`${file}: must be named after its id, ${parsed.doc.id}.grooph.json`);
  else docs.push({ file, doc: parsed.doc });
}
if (problems.length > 0) {
  console.error(problems.join("\n"));
  process.exit(1);
}

const index = templateIndex(docs.map(({ doc, file }) => templateIndexEntry(doc, file)));
const indexText = `${JSON.stringify(index, null, 2)}\n`;

const profile = (p) => `${p.cost} · ${p.speed} · ${p.rigor}`;
const cell = (text) => text.replace(/\|/g, "\\|");
const readme = `# Pattern library

The built-in templates: one graph document per named pattern from spec §10, each with a \`template\` block (docs/templates.md). Every pattern validates with no errors once its slots are filled with their examples; the warnings a pattern raises on purpose are listed in \`<id>.expect.json\` beside it. Gauntlet-style polish is \`taste-polish\`, one bounded entry among many, never a default.

Use one by name, without copying anything:

\`\`\`bash
grooph template list
grooph template show review-gate
grooph template use review-gate --name "Slugify" --set task="Add a slugify function." --set test-command="pnpm test" --set checklist=docs/REVIEW-CHECKLIST.md --out slugify.grooph.json
grooph template insert human-gated-irreversible --into slugify.grooph.json --set action="Merge the branch into main." --set irreversible=merge --write
\`\`\`

The library is published with the web app at <https://ryanjosephkamp.github.io/grooph/patterns/index.json>, so \`grooph template add <id>\` fetches one without a clone.

| Pattern | Kind | When to use | Cost · speed · rigor | Slots |
|---|---|---|---|---|
${index.templates
  .map(
    (t) =>
      `| [\`${t.id}\`](${t.file}) ${cell(t.title)} | ${t.kind} | ${cell(t.whenToUse)} | ${profile(t.profile)} | ${(t.slots ?? []).map((s) => `\`${s}\``).join(", ")} |`,
  )
  .join("\n")}

_Generated by \`scripts/patterns-index.mjs\` from the documents in this folder, like \`index.json\`. Edit a pattern, then run \`node scripts/patterns-index.mjs\`; CI fails when either file is stale._
`;

const outputs = [
  { path: join(dir, "index.json"), text: indexText },
  { path: join(dir, "README.md"), text: readme },
];

if (process.argv.includes("--check")) {
  const stale = outputs.filter(({ path, text }) => {
    try {
      return readFileSync(path, "utf8") !== text;
    } catch {
      return true;
    }
  });
  if (stale.length > 0) {
    console.error(
      `stale: ${stale.map(({ path }) => path.slice(root.length + 1)).join(", ")}; run \`node scripts/patterns-index.mjs\` and commit the result`,
    );
    process.exit(1);
  }
  console.log(`patterns/index.json and patterns/README.md are current (${index.templates.length} patterns)`);
} else {
  for (const { path, text } of outputs) writeFileSync(path, text, "utf8");
  console.log(`wrote patterns/index.json and patterns/README.md (${index.templates.length} patterns)`);
}
